version: "3.4"

services:
    web-app:
        build:
          context: .
          dockerfile: src/LanguageLearning.Web.Host/Dockerfile
        ports:
          - "8080:80"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_Kestrel__Certificates__Default__Password=E.deniz123
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        depends_on:
          - ms-sql

    ms-sql:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "E.deniz123"
            ACCEPT_EULA: "Y"