version: "3.4"

services:
    web-app:
        build:
          context: .
          dockerfile: src/LanguageLearning.Web.Host/Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - ms-sql

    ms-sql:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "E.deniz123"
            ACCEPT_EULA: "Y"